"""
Constraint propagation graph for bidirectional semantic inference.

Build a directed graph from JSON schema structure where nodes are schema
fields and edges encode semantic dependency relationships. When a field
value is committed (generated by the LLM), propagate domain reductions
forward and backward through the graph.

When a field's domain reduces to a single value it is DETERMINED — the
TTF engine can inject the computed value without generating it, eliminating
that class of hallucination.

Supported edge types:
  DERIVES_FROM  → parent value computed from child/array fields
  REQUIRED_IF   → field required conditionally (dependentSchemas, if/then)
  EXCLUSIVE     → fields that cannot both be active (oneOf mutual exclusion)
  ORDERED       → source must be committed before target (array before verdict)
  BOUNDS_VALUE  → source constrains target domain (minItems, numeric range)
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

# ---------------------------------------------------------------------------
# Edge taxonomy
# ---------------------------------------------------------------------------


class EdgeType(Enum):
    """Semantic relationship type for a directed edge in the graph."""

    DERIVES_FROM = "derives_from"
    """Target's value is computed from the source field values."""

    REQUIRED_IF = "required_if"
    """Target is required when source has a specific committed value."""

    EXCLUSIVE = "exclusive"
    """Source and target cannot both be active simultaneously."""

    ORDERED = "ordered"
    """Source must be generated/committed before target."""

    BOUNDS_VALUE = "bounds_value"
    """Source constrains target's domain (cardinality or numeric range)."""


# ---------------------------------------------------------------------------
# Public data contracts
# ---------------------------------------------------------------------------


@dataclass
class GraphEdge:
    """A directed semantic dependency edge in the constraint graph."""

    source: str
    """Field path that influences the target."""

    target: str
    """Field path that is influenced by the source."""

    edge_type: EdgeType

    metadata: dict[str, Any] = field(default_factory=dict)
    """Type-specific data: pattern, condition_value, bound values, etc."""


@dataclass
class DomainReduction:
    """Record of a domain reduction for one field during propagation."""

    field_path: str
    original_domain_size: int
    new_domain_size: int
    reason: str


@dataclass
class PropagationResult:
    """
    Result of a propagation pass on the constraint graph.

    Attributes
    ----------
    committed_fields:
        Field paths committed in this propagation.
    determined_fields:
        Fields whose domain reduced to a single value.  These can be
        computed/injected rather than generated.
    narrowed_enums:
        Enum fields with domains reduced to 2-3 values; useful for
        tightening retry constraints.
    inconsistencies:
        (field_path, reason) pairs where a committed value contradicts
        a propagation-derived domain constraint.
    reductions:
        All domain reductions that occurred during propagation.
    """

    committed_fields: list[str]
    determined_fields: dict[str, Any]
    narrowed_enums: dict[str, list[Any]]
    inconsistencies: list[tuple[str, str]]
    reductions: list[DomainReduction]


# ---------------------------------------------------------------------------
# Internal node representation (private)
# ---------------------------------------------------------------------------


@dataclass
class _FieldNode:
    """Internal graph node representing a schema field."""

    field_path: str
    field_type: str
    initial_domain: set[Any] | None  # None for unconstrained (strings, objects)
    current_domain: set[Any] | None
    enum_values: list[Any]
    committed: bool = False
    committed_value: Any = None

    def is_determined(self) -> bool:
        """True when domain has reduced to a single value but not yet committed."""
        return (
            self.current_domain is not None and len(self.current_domain) == 1 and not self.committed
        )

    def is_narrowed_enum(self) -> bool:
        """True when enum domain narrowed to 2-3 values from a wider set."""
        return (
            self.field_type == "enum"
            and self.current_domain is not None
            and 2 <= len(self.current_domain) <= 3
            and self.initial_domain is not None
            and len(self.initial_domain) > 3
        )


# ---------------------------------------------------------------------------
# Core graph
# ---------------------------------------------------------------------------


class ConstraintPropagationGraph:
    """
    Build and propagate semantic field constraints from JSON schema structure.

    Detects semantic dependencies between schema fields and propagates domain
    reductions when field values are committed.  The primary use cases are:

    1. **Incremental** (during generation): call ``propagate(field_path, value)``
       as each field value is generated.  When a child is committed with a
       fail/false value the parent verdict domain collapses immediately —
       enabling early termination or injection.

    2. **Batch** (post-generation): call ``propagate_batch(output)`` on a
       complete output dict to find inconsistencies and determined fields.

    Parameters
    ----------
    schema:
        JSON Schema dict (top-level object with ``"properties"``).
    """

    def __init__(self, schema: dict[str, Any]) -> None:
        self.schema = schema
        self._nodes: dict[str, _FieldNode] = {}
        self._edges: list[GraphEdge] = []
        self._propagation_trace: list[str] = []
        self._build_graph()

    # ------------------------------------------------------------------
    # Graph construction
    # ------------------------------------------------------------------

    def _build_graph(self) -> None:
        """Construct all nodes and edges from schema structure."""
        self._extract_fields(self.schema, "")
        self._detect_derives_from()
        self._detect_required_if()
        self._detect_exclusive()
        self._detect_bounds()

    def _extract_fields(self, schema: dict[str, Any], prefix: str) -> None:
        """Walk schema tree and register all leaf fields as nodes."""
        properties: dict[str, Any] = schema.get("properties") or {}
        for fname, fspec in properties.items():
            if not isinstance(fspec, dict):
                continue
            path = f"{prefix}.{fname}" if prefix else fname
            field_type: str = fspec.get("type") or "string"
            enum_values: list[Any] = fspec.get("enum") or []

            # Build initial domain
            domain: set[Any] | None = None
            if field_type == "boolean":
                domain = {True, False}
            elif enum_values:
                field_type = "enum"
                domain = set(enum_values)

            self._nodes[path] = _FieldNode(
                field_path=path,
                field_type=field_type,
                initial_domain=domain.copy() if domain is not None else None,
                current_domain=domain.copy() if domain is not None else None,
                enum_values=list(enum_values),
            )

            # Recurse into nested objects
            if field_type == "object":
                self._extract_fields(fspec, path)

            # Extract array item fields with wildcard path
            if fspec.get("type") == "array":
                items: Any = fspec.get("items") or {}
                if isinstance(items, dict) and "properties" in items:
                    self._extract_fields(items, f"{path}[*]")

    def _detect_derives_from(self) -> None:
        """
        Detect DERIVES_FROM edges using aggregation patterns.

        Reuses aggregation compiler detection to build edges:
        boolean parent + array[boolean items] → DERIVES_FROM(BOOLEAN_ALL)
        numeric parent + array[numeric items] → DERIVES_FROM(NUMERIC_SUM/MEAN)
        enum parent + array[same-enum items]  → DERIVES_FROM(ENUM_FAIL_ANY)
        """
        from formatshield.reasoning.aggregation_compiler import compile_aggregation_rules

        rules = compile_aggregation_rules(self.schema)
        for rule in rules:
            # Source: array item sub-field (wildcard path)
            source_path = f"{rule.array_field}[*].{rule.child_field}"
            target_path = rule.parent_field

            self._edges.append(
                GraphEdge(
                    source=source_path,
                    target=target_path,
                    edge_type=EdgeType.DERIVES_FROM,
                    metadata={
                        "pattern": rule.pattern.value,
                        "array_field": rule.array_field,
                        "child_field": rule.child_field,
                        "fail_values": rule.fail_values,
                    },
                )
            )

            # ORDERED: array must be committed before parent verdict
            self._edges.append(
                GraphEdge(
                    source=rule.array_field,
                    target=target_path,
                    edge_type=EdgeType.ORDERED,
                    metadata={"reason": "array items before parent verdict"},
                )
            )

    def _detect_required_if(self) -> None:
        """
        Detect REQUIRED_IF edges from ``if/then`` and ``dependentSchemas``.

        Example: ``"if": {"properties": {"type": {"const": "advanced"}}},
        "then": {"required": ["advanced_options"]}`` produces a REQUIRED_IF
        edge from ``type`` to ``advanced_options``.
        """
        # if/then pattern
        if_schema: dict[str, Any] = self.schema.get("if") or {}
        then_schema: dict[str, Any] = self.schema.get("then") or {}
        if_props: dict[str, Any] = if_schema.get("properties") or {}
        then_required: list[str] = then_schema.get("required") or []

        for if_field, if_constraint in if_props.items():
            if not isinstance(if_constraint, dict):
                continue
            const_val = if_constraint.get("const")
            if const_val is None:
                continue
            for req_field in then_required:
                self._edges.append(
                    GraphEdge(
                        source=if_field,
                        target=req_field,
                        edge_type=EdgeType.REQUIRED_IF,
                        metadata={"condition_value": const_val},
                    )
                )

        # dependentSchemas
        dependent: dict[str, Any] = self.schema.get("dependentSchemas") or {}
        for trigger_field, dep_schema in dependent.items():
            if not isinstance(dep_schema, dict):
                continue
            dep_required: list[str] = dep_schema.get("required") or []
            for req_field in dep_required:
                self._edges.append(
                    GraphEdge(
                        source=trigger_field,
                        target=req_field,
                        edge_type=EdgeType.REQUIRED_IF,
                        metadata={"condition": "field_present"},
                    )
                )

    def _detect_exclusive(self) -> None:
        """
        Detect EXCLUSIVE edges from ``oneOf`` with non-overlapping required sets.

        When each ``oneOf`` option has a distinct set of required fields, the
        fields from different options are mutually exclusive.
        """
        one_of: list[Any] = self.schema.get("oneOf") or []
        if len(one_of) < 2:
            return

        option_required: list[set[str]] = []
        for option in one_of:
            if isinstance(option, dict):
                req: set[str] = set(option.get("required") or [])
                if req:
                    option_required.append(req)

        for i, set_a in enumerate(option_required):
            for set_b in option_required[i + 1 :]:
                if not set_a & set_b:
                    for field_a in set_a:
                        for field_b in set_b:
                            self._edges.append(
                                GraphEdge(
                                    source=field_a,
                                    target=field_b,
                                    edge_type=EdgeType.EXCLUSIVE,
                                    metadata={},
                                )
                            )

    def _detect_bounds(self) -> None:
        """
        Detect BOUNDS_VALUE edges from ``minItems``/``maxItems`` on arrays.

        Array fields with cardinality constraints create BOUNDS_VALUE edges
        to the wildcard array item path.
        """
        properties: dict[str, Any] = self.schema.get("properties") or {}
        for fname, fspec in properties.items():
            if not isinstance(fspec, dict):
                continue
            if fspec.get("type") == "array":
                min_items: int | None = fspec.get("minItems")
                max_items: int | None = fspec.get("maxItems")
                if min_items is not None or max_items is not None:
                    self._edges.append(
                        GraphEdge(
                            source=fname,
                            target=f"{fname}[*]",
                            edge_type=EdgeType.BOUNDS_VALUE,
                            metadata={
                                "min_items": min_items,
                                "max_items": max_items,
                            },
                        )
                    )

    # ------------------------------------------------------------------
    # Propagation
    # ------------------------------------------------------------------

    def propagate(self, field_path: str, value: Any) -> PropagationResult:
        """
        Commit a single field value and propagate domain reductions.

        Parameters
        ----------
        field_path:
            Field path of the committed value.  Array item paths like
            ``"premises[0].valid"`` are matched against wildcard-form edges
            ``"premises[*].valid"``.
        value:
            Committed value.

        Returns
        -------
        PropagationResult
            Determined/narrowed fields and any inconsistencies after propagation.
        """
        result = PropagationResult(
            committed_fields=[field_path],
            determined_fields={},
            narrowed_enums={},
            inconsistencies=[],
            reductions=[],
        )

        # Mark the node as committed (if tracked as a named node)
        node = self._nodes.get(field_path)
        if node is not None:
            node.committed = True
            node.committed_value = value

        # Propagate via DERIVES_FROM edges
        visited: set[str] = set()
        self._propagate_derives_from(field_path, value, result, visited)

        # Collect determined and narrowed fields
        for path, nd in self._nodes.items():
            if path == field_path:
                continue
            if nd.is_determined():
                det_val = next(iter(nd.current_domain))  # type: ignore[arg-type]
                result.determined_fields[path] = det_val
                self._propagation_trace.append(f"  ✓ DETERMINED: {path}={det_val!r}")
            elif nd.is_narrowed_enum():
                result.narrowed_enums[path] = sorted(str(v) for v in (nd.current_domain or set()))

        return result

    def _propagate_derives_from(
        self,
        committed_path: str,
        committed_value: Any,
        result: PropagationResult,
        visited: set[str],
    ) -> None:
        """Follow DERIVES_FROM edges from a committed field path."""
        if committed_path in visited:
            return
        visited.add(committed_path)

        for edge in self._edges:
            if edge.edge_type != EdgeType.DERIVES_FROM:
                continue
            if not _path_matches(committed_path, edge.source):
                continue

            target_path = edge.target
            target_node = self._nodes.get(target_path)
            if target_node is None:
                continue

            self._apply_derives_from(edge, committed_path, committed_value, target_node, result)

    def _apply_derives_from(
        self,
        edge: GraphEdge,
        committed_path: str,
        committed_value: Any,
        target_node: _FieldNode,
        result: PropagationResult,
    ) -> None:
        """Reduce target domain based on the edge's aggregation pattern."""
        pattern: str = edge.metadata.get("pattern") or ""

        if pattern == "boolean_all" and target_node.field_type == "boolean":
            # BOOLEAN_ALL: if ANY child is False, parent MUST be False
            is_false = committed_value is False or str(committed_value).lower() in (
                "false",
                "0",
                "no",
            )
            if is_false and target_node.current_domain is not None:
                old_size = len(target_node.current_domain)
                target_node.current_domain = {False}
                reason = (
                    f"DERIVES_FROM(BOOLEAN_ALL): {committed_path}=false "
                    f"forces {target_node.field_path}=false"
                )
                result.reductions.append(
                    DomainReduction(
                        field_path=target_node.field_path,
                        original_domain_size=old_size,
                        new_domain_size=1,
                        reason=reason,
                    )
                )
                self._propagation_trace.append(f"  → {reason}")

                # Detect inconsistency: target already committed as True
                if target_node.committed and target_node.committed_value is True:
                    result.inconsistencies.append(
                        (
                            target_node.field_path,
                            f"{target_node.field_path}=true but {committed_path}=false "
                            f"(BOOLEAN_ALL violation)",
                        )
                    )

        elif pattern == "enum_fail_any" and target_node.field_type == "enum":
            fail_values: list[str] = edge.metadata.get("fail_values") or []
            fail_set_lower = {v.lower() for v in fail_values}
            committed_norm = (
                str(committed_value).lower() if isinstance(committed_value, str) else ""
            )

            if committed_norm in fail_set_lower and target_node.current_domain is not None:
                # Narrow target to only fail-class values in current domain
                fail_in_domain = {
                    v for v in target_node.current_domain if str(v).lower() in fail_set_lower
                }
                if fail_in_domain:
                    old_size = len(target_node.current_domain)
                    target_node.current_domain = fail_in_domain
                    reason = (
                        f"DERIVES_FROM(ENUM_FAIL_ANY): {committed_path}={committed_value!r} "
                        f"narrows {target_node.field_path} to fail-class values"
                    )
                    result.reductions.append(
                        DomainReduction(
                            field_path=target_node.field_path,
                            original_domain_size=old_size,
                            new_domain_size=len(fail_in_domain),
                            reason=reason,
                        )
                    )
                    self._propagation_trace.append(f"  → {reason}")

    def propagate_batch(self, output: dict[str, Any]) -> PropagationResult:
        """
        Propagate all field values from a complete output dict.

        Commits array item sub-fields first (they determine parent fields),
        then checks top-level fields against computed domains.

        Parameters
        ----------
        output:
            Complete parsed JSON output dict from Pass 2 generation.

        Returns
        -------
        PropagationResult
            All determined fields, narrowed enums, and detected inconsistencies.
        """
        self.reset()

        combined = PropagationResult(
            committed_fields=[],
            determined_fields={},
            narrowed_enums={},
            inconsistencies=[],
            reductions=[],
        )

        # Commit array item sub-fields first (inputs before derived parents)
        for array_name, array_val in output.items():
            if not isinstance(array_val, list):
                continue
            for i, item in enumerate(array_val):
                if not isinstance(item, dict):
                    continue
                for sub_field, sub_value in item.items():
                    item_path = f"{array_name}[{i}].{sub_field}"
                    r = self.propagate(item_path, sub_value)
                    combined.committed_fields.extend(r.committed_fields)
                    combined.reductions.extend(r.reductions)
                    # Collect propagation-derived inconsistencies early
                    combined.inconsistencies.extend(r.inconsistencies)

        # Commit top-level fields; detect domain violations
        for field_name, field_value in output.items():
            if isinstance(field_value, list):
                continue  # Already handled
            node = self._nodes.get(field_name)
            if node is not None and node.current_domain is not None and not node.committed:
                # Check committed value against propagation-reduced domain
                if field_value not in node.current_domain:
                    combined.inconsistencies.append(
                        (
                            field_name,
                            f"'{field_name}'={field_value!r} conflicts with "
                            f"propagation-derived domain "
                            f"{sorted(str(v) for v in node.current_domain)}",
                        )
                    )
            # Mark as committed
            r = self.propagate(field_name, field_value)
            combined.committed_fields.extend(r.committed_fields)
            combined.reductions.extend(r.reductions)

        # Collect final determined/narrowed fields (not in output)
        for path, nd in self._nodes.items():
            if path in combined.committed_fields:
                continue
            if nd.is_determined():
                det_val = next(iter(nd.current_domain))  # type: ignore[arg-type]
                combined.determined_fields[path] = det_val
            elif nd.is_narrowed_enum():
                combined.narrowed_enums[path] = sorted(str(v) for v in (nd.current_domain or set()))

        return combined

    # ------------------------------------------------------------------
    # Queries
    # ------------------------------------------------------------------

    def get_determined_fields(self) -> dict[str, Any]:
        """
        Return fields with single-value domains that have not been committed.

        These fields can be computed and injected directly without generation.
        """
        return {
            path: next(iter(nd.current_domain))  # type: ignore[arg-type]
            for path, nd in self._nodes.items()
            if nd.is_determined()
        }

    def get_narrowed_enums(self) -> dict[str, list[Any]]:
        """
        Return enum fields with domains reduced to 2-3 values.

        Useful for tightening enum constraints in a retry prompt.
        """
        return {
            path: sorted(str(v) for v in (nd.current_domain or set()))
            for path, nd in self._nodes.items()
            if nd.is_narrowed_enum()
        }

    def get_propagation_trace(self) -> list[str]:
        """Human-readable propagation trace for debugging and logging."""
        return list(self._propagation_trace)

    def get_edges(self) -> list[GraphEdge]:
        """Return all graph edges (copy)."""
        return list(self._edges)

    def get_node_count(self) -> int:
        """Return number of field nodes registered in the graph."""
        return len(self._nodes)

    def reset(self) -> None:
        """Reset committed state and restore initial domains for reuse."""
        self._propagation_trace.clear()
        for nd in self._nodes.values():
            nd.committed = False
            nd.committed_value = None
            nd.current_domain = nd.initial_domain.copy() if nd.initial_domain is not None else None


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------


def _path_matches(committed_path: str, edge_source: str) -> bool:
    """
    Return True if ``committed_path`` matches the ``edge_source`` pattern.

    Handles wildcard array paths: ``"premises[*].valid"`` matches
    ``"premises[0].valid"``, ``"premises[1].valid"``, etc.
    """
    if committed_path == edge_source:
        return True
    # Convert wildcard "[*]" to regex matching indexed "[N]"
    pattern = re.escape(edge_source).replace(r"\[\*\]", r"\[\d+\]")
    return bool(re.fullmatch(pattern, committed_path))


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def build_constraint_graph(schema: dict[str, Any]) -> ConstraintPropagationGraph:
    """
    Build a constraint propagation graph from a JSON schema.

    Parameters
    ----------
    schema:
        JSON Schema dict (top-level object schema).

    Returns
    -------
    ConstraintPropagationGraph
        Ready-to-use graph.  Call ``propagate()`` to commit field values
        incrementally or ``propagate_batch()`` on a complete output dict.

    Examples
    --------
    ::

        schema = {
            "properties": {
                "premises": {
                    "type": "array",
                    "items": {"properties": {"valid": {"type": "boolean"}}},
                },
                "argument_valid": {"type": "boolean"},
            }
        }
        cpg = build_constraint_graph(schema)

        # Incremental: commit each item as it is generated
        result = cpg.propagate("premises[0].valid", False)
        # → result.determined_fields == {"argument_valid": False}

        # Batch: verify a complete output
        output = {"premises": [{"valid": False}], "argument_valid": True}
        batch_result = cpg.propagate_batch(output)
        # → batch_result.inconsistencies contains "argument_valid=true vs domain {False}"
    """
    return ConstraintPropagationGraph(schema)
